# Generated by Django 2.0.7 on 2018-07-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='course',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
