# Generated by Django 2.0.7 on 2018-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20180805_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
