# Generated by Django 2.0.7 on 2018-08-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_slide_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='code',
        ),
    ]
