# Generated by Django 2.1.1 on 2018-09-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_slide_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_admin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_submit_time', models.DateTimeField(verbose_name='last sumbit date')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Answer')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Slide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSlideView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_time', models.DateTimeField(verbose_name='last viewed date')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Slide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.User')),
            ],
        ),
    ]
