# Generated by Django 2.1.1 on 2018-09-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('lms', '0011_auto_20180922_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
