# Generated by Django 2.1.1 on 2019-01-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_slidetype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='item',
        ),
    ]
