# Generated by Django 3.0.5 on 2020-05-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_usercoursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursestatus',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
    ]
