# Generated by Django 2.0.7 on 2018-07-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20180729_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
        ),
    ]
