# Generated by Django 2.0.7 on 2018-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_num',
            field=models.IntegerField(default=0),
        ),
    ]
