# Generated by Django 2.1.1 on 2018-10-28 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0012_client_users_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('last_modified_time', models.DateTimeField(blank=True, null=True, verbose_name='last modified time')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='main_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='main_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='main_phone',
        ),
        migrations.RemoveField(
            model_name='course',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='client',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Client'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='course',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='publication_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='itempropertyvalue',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Item'),
        ),
        migrations.AddField(
            model_name='slide',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slide',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
        migrations.AddField(
            model_name='slide',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Slide'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Item'),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='item_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.ItemProperty'),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modified time'),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempropertyvalue',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='next_slide_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='previous_slide_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='last_submit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last submit date'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Slide'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userslideview',
            name='last_view_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last viewed date'),
        ),
        migrations.AlterField(
            model_name='userslideview',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Slide'),
        ),
        migrations.AlterField(
            model_name='userslideview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Client'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='modified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.CourseStatus'),
        ),
        migrations.AddField(
            model_name='item',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Catalogue'),
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Catalogue'),
        ),
    ]
