# Generated by Django 2.1.1 on 2018-12-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20181028_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.SlideType'),
        ),
    ]
