# Generated by Django 2.1.1 on 2019-05-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_auto_20190126_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Test'),
        ),
    ]
